In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [62]:
df.describe().round()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.0,768.0,768.0,768.0,768.0,768.0,768.0,768.0,768.0
mean,4.0,121.0,69.0,21.0,80.0,32.0,0.0,33.0,0.0
std,3.0,32.0,19.0,16.0,115.0,8.0,0.0,12.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0
25%,1.0,99.0,62.0,0.0,0.0,27.0,0.0,24.0,0.0
50%,3.0,117.0,72.0,23.0,30.0,32.0,0.0,29.0,0.0
75%,6.0,140.0,80.0,32.0,127.0,37.0,1.0,41.0,1.0
max,17.0,199.0,122.0,99.0,846.0,67.0,2.0,81.0,1.0

In [63]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age', 'outcome'],
      dtype='str')

In [64]:
df.outcome.value_counts()

outcome
0    500
1    268
Name: count, dtype: int64

In [65]:
cols = ['glucose','bloodpressure', 'skinthickness', 'insulin', 'bmi']
df[cols] = df[cols].replace(0, np.nan)

In [66]:
df.isnull().sum()

pregnancies                   0
glucose                       5
bloodpressure                35
skinthickness               227
insulin                     374
bmi                          11
diabetespedigreefunction      0
age                           0
outcome                       0
dtype: int64

In [67]:
cols = ['glucose','bloodpressure', 'skinthickness', 'insulin', 'bmi']
for col in cols:
    df[col]=df[col].replace(np.nan, df[col].median())

In [68]:
from sklearn.model_selection import train_test_split
from sklearn.utils import resample

In [69]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=5)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=5)

In [70]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [71]:
df_train.outcome.value_counts()

outcome
0    305
1    155
Name: count, dtype: int64

In [72]:
max = df_train[df_train.outcome==0]
min = df_train[df_train.outcome==1]
upsample = resample(min, replace=True, n_samples=305, random_state=7)
df_train = pd.concat([upsample, max])

In [74]:
y_train = df_train.outcome
y_val = df_val.outcome
y_test = df_test.outcome

In [75]:
df_train.outcome.value_counts()

outcome
1    305
0    305
Name: count, dtype: int64

In [76]:
del df_train['outcome']
del df_val['outcome']
del df_test['outcome']

In [77]:
len(df_train), len(df_test), len(df_val)

(610, 154, 154)

In [78]:
X_train = df_train
X_val = df_val
X_test = df_test

In [82]:
y_train.value_counts()

outcome
1    305
0    305
Name: count, dtype: int64